package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/spf13/cobra"
)

const prepareCommitMsgHook = `#!/bin/sh
# Auto-generated by aiu enable-auto-commit
# AI-powered commit message generation

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"

# Skip if AI_IGNORE=1
if [ "${AI_IGNORE:-0}" = "1" ]; then
    exit 0
fi

# Skip for merge, squash, or amend commits
if [ "$COMMIT_SOURCE" = "merge" ] || [ "$COMMIT_SOURCE" = "squash" ]; then
    exit 0
fi

# Skip if commit message already provided (amend or -m flag)
if [ "$COMMIT_SOURCE" = "commit" ] || [ -n "$COMMIT_SOURCE" ]; then
    exit 0
fi

# Check if there are staged changes
if ! git diff --cached --quiet 2>/dev/null; then
    # Generate commit message using AI
    AI_MSG=$(aiu run commit-msg 2>/dev/null)
    if [ -n "$AI_MSG" ]; then
        echo "$AI_MSG" > "$COMMIT_MSG_FILE"
    fi
fi
`

var enableAutoCommitCmd = &cobra.Command{
	Use:   "enable-auto-commit",
	Short: "Enable AI-powered commit message generation globally",
	Long: `Enable AI-powered commit message generation for all git repositories.

This sets up a global git hook that automatically generates commit messages
using AI whenever you run 'git commit' in any repository.

To skip AI generation for a specific commit, use:
  AI_IGNORE=1 git commit

Examples:
  aiu enable-auto-commit     # Enable globally
  aiu disable-auto-commit    # Disable globally`,
	RunE: runEnableAutoCommit,
}

var disableAutoCommitCmd = &cobra.Command{
	Use:   "disable-auto-commit",
	Short: "Disable AI-powered commit message generation",
	Long:  `Disable the global git hook for AI-powered commit message generation.`,
	RunE:  runDisableAutoCommit,
}

func init() {
	rootCmd.AddCommand(enableAutoCommitCmd)
	rootCmd.AddCommand(disableAutoCommitCmd)
}

func getGlobalHooksDir() (string, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(homeDir, ".config", "aiu", "hooks"), nil
}

func runEnableAutoCommit(cmd *cobra.Command, args []string) error {
	hooksDir, err := getGlobalHooksDir()
	if err != nil {
		return fmt.Errorf("failed to get hooks directory: %w", err)
	}

	// Create hooks directory
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	// Write the hook
	hookPath := filepath.Join(hooksDir, "prepare-commit-msg")
	if err := os.WriteFile(hookPath, []byte(prepareCommitMsgHook), 0755); err != nil {
		return fmt.Errorf("failed to write hook: %w", err)
	}

	// Set global git config
	gitCmd := exec.Command("git", "config", "--global", "core.hooksPath", hooksDir)
	if err := gitCmd.Run(); err != nil {
		return fmt.Errorf("failed to set git config: %w", err)
	}

	fmt.Println("✅ AI-powered commit message generation enabled globally!")
	fmt.Printf("   Hook installed at: %s\n", hookPath)
	fmt.Println()
	fmt.Println("Now 'git commit' will automatically generate commit messages in any repository.")
	fmt.Println()
	fmt.Println("To skip AI for a specific commit:")
	fmt.Println("  AI_IGNORE=1 git commit")
	fmt.Println()
	fmt.Println("To disable:")
	fmt.Println("  aiu disable-auto-commit")

	return nil
}

func runDisableAutoCommit(cmd *cobra.Command, args []string) error {
	// Unset global git config
	gitCmd := exec.Command("git", "config", "--global", "--unset", "core.hooksPath")
	_ = gitCmd.Run() // Ignore error if not set

	// Optionally remove hooks directory
	hooksDir, err := getGlobalHooksDir()
	if err == nil {
		os.RemoveAll(hooksDir)
	}

	fmt.Println("✅ AI-powered commit message generation disabled.")
	fmt.Println()
	fmt.Println("To re-enable:")
	fmt.Println("  aiu enable-auto-commit")

	return nil
}
